title: Paxton's Notes
description: Coding Notes
theme: just-the-docs
source: .
gist:
  noscript: false

#url: https://paxtonb.com
url: https://14paxton.github.io
aux_links:
  Template Repository: https://github.com/14paxton/14paxton.github.io
aux_links_new_tab: true

# Conversion
markdown            : kramdown
#highlighter         : rouge
highlighter         : coderay
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false
kramdown:
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    block:
      line_numbers: true
    line_numbers: table
    bold_every: 5
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  hard_wrap         : true
  footnote_nr       : 1
  show_warnings     : true

# just-the-docs template config
# Color scheme supports "light" (default) and "dark"
compress_html:
  ignore:
    envs: all
color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red


plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - kramdown-syntax-coderay

relative_links:
  enabled: true
  collections: true


