lsi: false
safe: true
source: docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
markdown: kramdown
title: Paxton's Notes
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
