plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
