lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
title: Paxton's Notes
plugins:
  jekyll-relative-links
relative_links:
  enabled: true
  collections: true
