lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Paxton's Notes
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
relative_links:
  enabled: true
  collections: true
