title: Paxton's Notes
description: Coding Notes
theme: just-the-docs

url: https://14paxton.github.io
aux_links:
  Template Repository: https://14paxton.github.io

plugins:
  - jekyll-default-layout


