title: Paxton's Notes
description: Coding Notes
theme: just-the-docs
#source: .
#incremental: false
#gist:
#  noscript: false

url: https://paxtonb.com
#url: https://14paxton.github.io
aux_links:
  Template Repository: https://github.com/14paxton/14paxton.github.io
aux_links_new_tab: true

# Conversion
markdown            : kramdown
lsi                 : false
excerpt_separator   : "\n\n"
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
  #  bold_every: 5
#  auto_ids          : true
#  entity_output     : as_char
#  toc_levels        : [1, 2, 3, 4, 5, 6]
#  smart_quotes      : lsquo,rsquo,ldquo,rdquo
#  hard_wrap         : true
#  footnote_nr       : 1
#  show_warnings     : true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red


plugins:
  - jekyll-default-layout
#  - jekyll-github-metadata
  - kramdown-syntax-coderay

#relative_links:
#  enabled: true
#  collections: true


