source 'https://rubygems.org'

gem 'json', '~> 2.6', '>= 2.6.3'
gem 'jekyll', '~> 4.3', '>= 4.3.2'
gem 'webrick', '~> 1.8', '>= 1.8.1'
gem 'jekyll-default-layout', '~> 0.1.5'
gem 'jekyll-github-metadata'
gem 'jekyll-watch'
gem 'kramdown', '~> 2.4'
gem 'kramdown-parser-gfm'
# gem 'coderay', '~> 1.1', '>= 1.1.3'
# gem 'kramdown-syntax-coderay', '~> 1.0', '>= 1.0.1'
gem 'rouge', '~> 4.2'
gem 'just-the-docs', '~> 0.7.0'
gem 'wdm', '>= 0.1.1' if Gem.win_platform?